In [8]:
import pandas as pd
import numpy as np
import string

In [9]:
products = pd.read_csv('amazon_baby_subset.csv')

In [10]:
products['name'].head(10).values

array(["Stop Pacifier Sucking without tears with Thumbuddy To Love's Binky Fairy Puppet and Adorable Book",
       "Nature's Lullabies Second Year Sticker Calendar",
       "Nature's Lullabies Second Year Sticker Calendar",
       'Lamaze Peekaboo, I Love You',
       "SoftPlay Peek-A-Boo Where's Elmo A Children's Book",
       'Our Baby Girl Memory Book',
       'Hunnt&reg; Falling Flowers and Birds Kids Nursery Home Decor Vinyl Mural Art Wall Paper Stickers',
       'Blessed By Pope Benedict XVI Divine Mercy Full Color Medal',
       'Cloth Diaper Pins Stainless Steel Traditional Safety Pin (Black)',
       'Cloth Diaper Pins Stainless Steel Traditional Safety Pin (Black)'],
      dtype=object)

In [11]:
products.columns.values

array(['name', 'review', 'rating', 'sentiment'], dtype=object)

In [12]:
def remove_punctuation(text):
    table = str.maketrans({key: None for key in string.punctuation})
    return text.translate(table) 

In [13]:
products = products.fillna({'review':''})

In [14]:
products['review_clean'] = products['review'].apply(remove_punctuation)

In [15]:
important_words = pd.read_json('important_words.json')

In [16]:
important_words = important_words[0].tolist()

In [17]:
important_words

['baby',
 'one',
 'great',
 'love',
 'use',
 'would',
 'like',
 'easy',
 'little',
 'seat',
 'old',
 'well',
 'get',
 'also',
 'really',
 'son',
 'time',
 'bought',
 'product',
 'good',
 'daughter',
 'much',
 'loves',
 'stroller',
 'put',
 'months',
 'car',
 'still',
 'back',
 'used',
 'recommend',
 'first',
 'even',
 'perfect',
 'nice',
 'bag',
 'two',
 'using',
 'got',
 'fit',
 'around',
 'diaper',
 'enough',
 'month',
 'price',
 'go',
 'could',
 'soft',
 'since',
 'buy',
 'room',
 'works',
 'made',
 'child',
 'keep',
 'size',
 'small',
 'need',
 'year',
 'big',
 'make',
 'take',
 'easily',
 'think',
 'crib',
 'clean',
 'way',
 'quality',
 'thing',
 'better',
 'without',
 'set',
 'new',
 'every',
 'cute',
 'best',
 'bottles',
 'work',
 'purchased',
 'right',
 'lot',
 'side',
 'happy',
 'comfortable',
 'toy',
 'able',
 'kids',
 'bit',
 'night',
 'long',
 'fits',
 'see',
 'us',
 'another',
 'play',
 'day',
 'money',
 'monitor',
 'tried',
 'thought',
 'never',
 'item',
 'hard',
 'plasti

In [18]:
for word in important_words:
    products[word] = products['review_clean'].apply(lambda s : s.split().count(word))

In [19]:
products.columns.values

array(['name', 'review', 'rating', 'sentiment', 'review_clean', 'baby',
       'one', 'great', 'love', 'use', 'would', 'like', 'easy', 'little',
       'seat', 'old', 'well', 'get', 'also', 'really', 'son', 'time',
       'bought', 'product', 'good', 'daughter', 'much', 'loves',
       'stroller', 'put', 'months', 'car', 'still', 'back', 'used',
       'recommend', 'first', 'even', 'perfect', 'nice', 'bag', 'two',
       'using', 'got', 'fit', 'around', 'diaper', 'enough', 'month',
       'price', 'go', 'could', 'soft', 'since', 'buy', 'room', 'works',
       'made', 'child', 'keep', 'size', 'small', 'need', 'year', 'big',
       'make', 'take', 'easily', 'think', 'crib', 'clean', 'way',
       'quality', 'thing', 'better', 'without', 'set', 'new', 'every',
       'cute', 'best', 'bottles', 'work', 'purchased', 'right', 'lot',
       'side', 'happy', 'comfortable', 'toy', 'able', 'kids', 'bit',
       'night', 'long', 'fits', 'see', 'us', 'another', 'play', 'day',
       'money', 'moni

In [20]:
len(products[products['perfect'] >= 1])

2955

In [21]:
def get_numpy_data(dataframe, features, label):
    dataframe['constant'] = 1
    features = ['constant'] + features
    features_frame = dataframe[features]
    feature_matrix = features_frame.as_matrix()
    label_sarray = dataframe[label]
    label_array = label_sarray.as_matrix()
    return(feature_matrix, label_array)

In [22]:
feature_matrix, sentiment = get_numpy_data(products, important_words, 'sentiment')

/Users/mac/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """
/Users/mac/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  import sys


In [23]:
feature_matrix

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [24]:
sentiment

array([ 1,  1,  1, ..., -1, -1, -1])

In [25]:
feature_matrix.shape

(53072, 194)

In [1]:
'''
produces probablistic estimate for P(y_i = +1 | x_i, w).
estimate ranges between 0 and 1.
'''
def predict_probability(feature_matrix, coefficients):
    # Take dot product of feature_matrix and coefficients  
    # YOUR CODE HERE
    score = np.dot(feature_matrix, coefficients)
    
    # Compute P(y_i = +1 | x_i, w) using the link function
    # YOUR CODE HERE
    predictions = 1/(1+np.exp(-score))
    
    # return predictions
    return predictions

In [2]:
def feature_derivative(errors, feature):     
    # Compute the dot product of errors and feature
    derivative = np.dot(feature, errors)
        # Return the derivative
    return derivative

In [4]:
def compute_log_likelihood(feature_matrix, sentiment, coefficients):
    indicator = (sentiment==+1)
    scores = np.dot(feature_matrix, coefficients)
    lp = np.sum((indicator-1)*scores - np.log(1. + np.exp(-scores)))
    return lp

In [27]:
from math import sqrt
def logistic_regression(feature_matrix, sentiment, initial_coefficients, step_size, max_iter):
    coefficients = np.array(initial_coefficients) # make sure it's a numpy array
    for itr in range(max_iter):
        # Predict P(y_i = +1|x_1,w) using your predict_probability() function
        # YOUR CODE HERE
        predictions = predict_probability(feature_matrix, coefficients)

        # Compute indicator value for (y_i = +1)
        indicator = (sentiment==+1)

        # Compute the errors as indicator - predictions
        errors = indicator - predictions

        for j in range(len(coefficients)): # loop over each coefficient
            # Recall that feature_matrix[:,j] is the feature column associated with coefficients[j]
            # compute the derivative for coefficients[j]. Save it in a variable called derivative
            # YOUR CODE HERE
            derivative = feature_derivative(errors,feature_matrix[:,j])

            # add the step size times the derivative to the current coefficient
            # YOUR CODE HERE
            coefficients[j]+=derivative*step_size

        # Checking whether log likelihood is increasing
        if itr <= 15 or (itr <= 100 and itr % 10 == 0) or (itr <= 1000 and itr % 100 == 0) \
        or (itr <= 10000 and itr % 1000 == 0) or itr % 10000 == 0:
            lp = compute_log_likelihood(feature_matrix, sentiment, coefficients)
            print('iteration %*d: log likelihood of observed labels = %.8f' % \
                (int(np.ceil(np.log10(max_iter))), itr, lp))
    return coefficients

In [28]:
coefficients = logistic_regression(feature_matrix, sentiment, [0.0]*194, 1e-7, 301)

iteration   0: log likelihood of observed labels = -36780.91768478
iteration   1: log likelihood of observed labels = -36775.13434712
iteration   2: log likelihood of observed labels = -36769.35713564
iteration   3: log likelihood of observed labels = -36763.58603240
iteration   4: log likelihood of observed labels = -36757.82101962
iteration   5: log likelihood of observed labels = -36752.06207964
iteration   6: log likelihood of observed labels = -36746.30919497
iteration   7: log likelihood of observed labels = -36740.56234821
iteration   8: log likelihood of observed labels = -36734.82152213
iteration   9: log likelihood of observed labels = -36729.08669961
iteration  10: log likelihood of observed labels = -36723.35786366
iteration  11: log likelihood of observed labels = -36717.63499744
iteration  12: log likelihood of observed labels = -36711.91808422
iteration  13: log likelihood of observed labels = -36706.20710739
iteration  14: log likelihood of observed labels = -36700.5020

In [37]:
predication = np.dot(feature_matrix, coefficients)

In [38]:
predication

array([ 0.05104571, -0.02936473,  0.02411584, ..., -0.40986295,
        0.01411436, -0.06755923])

In [40]:
products['predication'] = 0
products['predication'][predication>0] = 1
products['predication'][predication<=0] = -1

/Users/mac/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/Users/mac/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [41]:
len(products[products['predication'] ==1 ])

25126

In [42]:
len(products[products['predication'] == products['sentiment']]) / len(products)

0.7518653904130238

In [43]:
coefficients = list(coefficients[1:]) # exclude intercept
word_coefficient_tuples = [(word, coefficient) for word, coefficient in zip(important_words, coefficients)]
word_coefficient_tuples = sorted(word_coefficient_tuples, key=lambda x:x[1], reverse=True)

In [44]:
word_coefficient_tuples

[('great', 0.0665460841704577),
 ('love', 0.06589076292212327),
 ('easy', 0.06479458680257838),
 ('little', 0.045435626308421365),
 ('loves', 0.04497640139490604),
 ('well', 0.03013500109210707),
 ('perfect', 0.029739937104968462),
 ('old', 0.02007754103477538),
 ('nice', 0.018408707995268992),
 ('daughter', 0.017703199905701694),
 ('soft', 0.01757027224560289),
 ('fits', 0.016882471071408715),
 ('happy', 0.01680529588976808),
 ('baby', 0.0155656965804235),
 ('recommend', 0.015408450108008663),
 ('also', 0.015216196422918847),
 ('best', 0.014991791565630266),
 ('comfortable', 0.013253990081584899),
 ('car', 0.012685935745813372),
 ('clean', 0.012018174433365527),
 ('son', 0.011944817713693955),
 ('bit', 0.011708248093123262),
 ('works', 0.011703160621987422),
 ('size', 0.010715966516270303),
 ('stroller', 0.009909164635972733),
 ('room', 0.009783241021568061),
 ('price', 0.009572733543590176),
 ('play', 0.009178428983984311),
 ('easily', 0.009032818138954407),
 ('kids', 0.0085828430043

In [45]:
word_coefficient_tuples = [(word, coefficient) for word, coefficient in zip(important_words, coefficients)]
word_coefficient_tuples = sorted(word_coefficient_tuples, key=lambda x:x[1], reverse=False)
word_coefficient_tuples

[('would', -0.053860148445203135),
 ('product', -0.0415110333921089),
 ('money', -0.038982037286487116),
 ('work', -0.03306951529475273),
 ('even', -0.0300512492360358),
 ('disappointed', -0.028978976142317068),
 ('get', -0.02871155298019259),
 ('back', -0.027742697230661327),
 ('return', -0.026592778462247283),
 ('monitor', -0.024482100545891717),
 ('waste', -0.024042748071154956),
 ('thought', -0.021394348543682478),
 ('could', -0.019846256660777214),
 ('tried', -0.018702371424325834),
 ('way', -0.018359460662945686),
 ('time', -0.018246193486087036),
 ('buy', -0.017737543997218042),
 ('item', -0.01713786701085479),
 ('returned', -0.016001798500102516),
 ('broke', -0.01553769895565389),
 ('better', -0.015040658977043384),
 ('plastic', -0.014977044903587942),
 ('reviews', -0.014866319449976984),
 ('cheap', -0.014709833465080667),
 ('thing', -0.013868727265297582),
 ('hard', -0.013756676731261403),
 ('first', -0.01321347530167704),
 ('never', -0.012969046546319297),
 ('something', -0.0